### ISSUE TITLE
Incorrect licence for blender addon

### ISSUE THREAD

**Issue by danemadsen** [Premik/blender_rhubarb_lipsync_ng#6]
Hi, thanks for taking over the development of this addon. I just wanted to let you know that you arnt allowed to use the MIT licence for blender addons. Blender addons must be released under a GPL v3 compatible licence and cannot be released under a permissive licence. This is due to addons using the blender API which is GPL software.

from blenders website:
```
Sharing or selling Blender add-ons (Python scripts)

Blender’s Python API is an integral part of the software, used to define the user interface or develop tools for example. The GNU GPL license therefore requires that such scripts (if published) are being shared under a GPL compatible license. You are free to sell such scripts, but the sales then is restricted to the download service itself. Your customers will receive the script under the same license (GPL), with the same free conditions as everyone has for Blender.
```

https://www.blender.org/about/license/

**Comment by Premik** [comment]
Hi Dane,
Thanks for the report. I found licensing around Blender to be bit tricky :)

>>Blender addons must be released under a GPL v3 compatible license 

MIT **is** [GPL compatible](https://en.wikipedia.org/wiki/MIT_License). Note even blender marketplace offers MIT as an option for plugins: https://blendermarket.com/page/mit-license

Having said that the difference between MIT and GPL in the blender plugins context is negligible. From my limited understanding it makes no difference in practice.
Anybody could make a their own version of this plugin and indeed they would not be bound by the MIT to release the source code beside their distribution. Nevertheless provided they'd be still using Blender API in their version they would stil have to release the sources anyway. Because of the Blender license requirements which would still apply.
